### ISSUE TITLE
Version 1.2.0 does not export function on worker instance in production mode

### ISSUE THREAD

**Issue by leifg** [developit/workerize-loader#85]
I just upgraded to workerize-loader v1.2.0

When the worker instance is created, it does not have the exported functions attached to it.

All this only happens in the production build (development server works fine)

This the the output of `console.log(instance)` in development server (`parseFormula` is the exported function):

```
Worker {onmessage: null, onerror: null, parseFormula: ƒ}
  onerror: null
  onmessage: null
  parseFormula: ƒ ()
__proto__: Worker
```

When creating a production build, this is the output:

```
Worker {onmessage: null, onerror: null}
  onerror: null
  onmessage: null
  __proto__: Worker
```

I have a suspicion it might have something to do with [this commit](https://github.com/developit/workerize-loader/commit/d7c85f93a32ec6893d5e4d1839efd5d85be60d2c) but I don't know enough about the project.

I call the worker [like this](https://github.com/leifg/formulon-frontend/blob/master/src/App.js#L29)

the worker function is defined [like this](https://github.com/leifg/formulon-frontend/blob/master/src/workers/formulaWorker.js)

I know I am using the API differently than described in the README, however all of this worked in 1.1.0 and I also converted the examples exactly like described and it still did not export the function in 1.2.0.

**Comment by hlolli** [comment]
I was going to open a ticket too :D, all I can say, is that this is happening to me too. I can't see any exported function in my worker instance. But I could see everything in 1.1.0. That said, happy to see this project maintained, and hope it will work with webpack 5 in near future.

**Comment by bilwit** [comment]
I have the same issue. I forced` "workerize-loader": "~1.1.0"` in my `package.json` and it works perfectly fine after the build.

**Comment by developit** [comment]
Yikes! I'll take a look.

**Comment by shareefalis** [comment]
You could basically do

 ```
 if node is production build
{ don't export as a local cache object} 
 else 
{ export as a local cache object }  
```

but that is a quick and dirty fix..

**Comment by developit** [comment]
A fix has been published in [1.2.1](https://github.com/developit/workerize-loader/releases/tag/1.2.1). Thanks all.

**Comment by titocosta** [comment]
Whenever there is a syntax error in the web worker file, you will see a "x is not a function" error first. So if you land here from google, check the web worker file first, problem on workerize was indeed fixed.
